### ISSUE TITLE
Edit menu should close

### ISSUE THREAD

**Issue by tarsisazevedo** [lusac/LiveEditor#25]
Edit menu is always opened even when page reload.

**Comment by hugoantunes** [comment]
@tarsisazevedo and @lusac,

I made some tests and now is working. check if something is missing.

[]'s

**Comment by tarsisazevedo** [comment]
It's works for me, but selected box still marked when I leave editor. And can you add tests for this?

![screen shot 2016-03-03 at 11 30 00 am](https://cloud.githubusercontent.com/assets/118348/13497287/5150b67e-e133-11e5-9e9a-22569e1883d1.png)
![screen shot 2016-03-03 at 11 29 53 am](https://cloud.githubusercontent.com/assets/118348/13497288/5162d46c-e133-11e5-9e91-0f0ec2780322.png)

**Comment by hugoantunes** [comment]
Guys, I found this function **`unselectElements`** and I changed the behaviour of the Event to work as @tarsisazevedo said.

But when I repeated the test some times, for some reason that i don't get it, the area selection area selection didn't work more.

Could anyone test too ?

@lusac @darlenedms
